excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://TCSYayvo.github.io
title: Yayvo Shopping Website Blog 
tagline: You think it - we have it ... News & Brand New!!
description: Check out the brand new tips and stories floating around the tech and fashion industry!!
paginate: 5